### ISSUE TITLE
Figuring out how to add a database and what I need to store.

### ISSUE THREAD

**Issue by horinet** [Berea-CS-Courses/capstone-project-horinet#20]
Firebase most likely

**Comment by smanalai** [comment]
You usually use a database to store information such as user email, username, or password. You can also use it to save user's activities, posts, and etc. It really depends on the kind of app you are building. Some of the databases that I am familiar with are PostgreSQL and MongoDB.  For app development with android studio, I used Parse which is a mobile backend as a service platform. Parse is basically like other databases. Let me know if you need more information on how to use Parse.

**Comment by horinet** [comment]
I am using firebase. I currently have login/logout/register account created in the firebaseimp branch. Still working on that branch. I am going to need to store the data in the app, the addtasksscreen. I have it commented what I need to implement, what is currently happening in the functions and how I need to change it.
