### ISSUE TITLE
Add Firebase code for user login/ logout/ register account

### ISSUE THREAD

**Issue by horinet** [Berea-CS-Courses/capstone-project-horinet#23]
https://firebase.google.com/docs/auth/android/start
https://firebase.google.com/docs/auth/android/password-auth?authuser=0
I have the login screen, but still figuring out how to get it working with the database :)

**Comment by jazzij** [comment]
To link this issue to your code, please add the issue number to the commit description (i.e. "#23 added login screen, no user validation yet")

**Comment by jazzij** [comment]
@belainehi would be a good person to tap for tips on how to save and validate user information with Firebase

**Comment by horinet** [comment]
I have implemented this today. I will link this to the pull request once created.
